import { useEffect, useState, useCallback } from "react";
import { FileText, Loader2, Copy, Download } from "lucide-react";
import { format } from "date-fns";
import DashboardLayout from "@/components/dashboard/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useAuth } from "@/hooks/useAuth";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";

const PLATFORMS = ["YouTube", "Instagram", "TikTok", "Facebook", "X/Twitter", "LinkedIn", "OnlyFans", "Fiverr", "Other"];

const DmcaGeneratorPage = () => {
  const { user } = useAuth();
  const { toast } = useToast();
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [notice, setNotice] = useState("");

  const [form, setForm] = useState({
    legal_name: "",
    email: "",
    platform: "",
    infringing_url: "",
    description: "",
  });

  useEffect(() => {
    if (!user) return;
    (async () => {
      const { data } = await supabase
        .from("profiles")
        .select("legal_name, full_name")
        .eq("user_id", user.id)
        .maybeSingle();
      setForm((f) => ({
        ...f,
        legal_name: data?.legal_name || data?.full_name || "",
        email: user.email || "",
      }));
      setLoading(false);
    })();
  }, [user]);

  const generateNotice = useCallback(async () => {
    if (!user) return;
    if (!form.legal_name.trim() || !form.email.trim() || !form.platform || !form.infringing_url.trim() || !form.description.trim()) {
      toast({ title: "Please fill in all fields", variant: "destructive" });
      return;
    }

    setGenerating(true);
    const today = format(new Date(), "MMMM d, yyyy");

    const text = `DMCA TAKEDOWN NOTICE
Pursuant to 17 U.S.C. § 512(c)

Date: ${today}

To Whom It May Concern:

I, ${form.legal_name}, am writing to notify you of an infringement of my copyrighted work(s) hosted on your platform (${form.platform}).

1. IDENTIFICATION OF COPYRIGHTED WORK

The original copyrighted work being infringed is described as follows:

${form.description}

This work is owned by ${form.legal_name} and is protected under United States copyright law.

2. IDENTIFICATION OF INFRINGING MATERIAL

The infringing material is located at the following URL:

${form.infringing_url}

I request that this material be immediately removed or access to it be disabled.

3. CONTACT INFORMATION

Name: ${form.legal_name}
Email: ${form.email}

4. GOOD FAITH STATEMENT

I have a good faith belief that the use of the copyrighted material described above is not authorized by the copyright owner, its agent, or the law.

5. ACCURACY STATEMENT

I swear, under penalty of perjury, that the information in this notification is accurate and that I am the copyright owner, or am authorized to act on behalf of the owner, of an exclusive right that is allegedly infringed.

6. ELECTRONIC SIGNATURE

/s/ ${form.legal_name}
Date: ${today}

---
This DMCA notice was generated by ClaimMyFace.com as a tool for performers protecting their identity and likeness rights. ClaimMyFace is not a law firm and this document does not constitute legal advice. Consult a qualified attorney before sending.`;

    // Save to database
    const { error } = await supabase.from("dmca_notices").insert({
      user_id: user.id,
      platform: form.platform,
      infringing_url: form.infringing_url.trim(),
      notice_text: text,
    });

    // Append to tamper-proof action log (hashed URL, never plaintext).
    try {
      const { sha256Hex } = await import("@/lib/urlHash");
      const url_hash = await sha256Hex(form.infringing_url.trim());
      await supabase.from("finding_actions").insert({
        user_id: user.id,
        url_hash,
        action_type: "dmca",
        status: "sent",
        notes: `Platform: ${form.platform}`,
      });
    } catch (e) { console.warn("[dmca] action log insert failed", e); }

    setGenerating(false);
    if (error) {
      toast({ title: "Save failed", description: error.message, variant: "destructive" });
    } else {
      setNotice(text);
      toast({ title: "DMCA notice generated and saved" });
    }
  }, [user, form, toast]);
  }, [user, form, toast]);

  const copyToClipboard = useCallback(async () => {
    await navigator.clipboard.writeText(notice);
    toast({ title: "Copied to clipboard" });
  }, [notice, toast]);

  const downloadPDF = useCallback(async () => {
    try {
      const { default: jsPDF } = await import("jspdf");
      const doc = new jsPDF({ unit: "mm", format: "a4" });
      const w = doc.internal.pageSize.getWidth();

      // Header
      doc.setFillColor(11, 21, 38);
      doc.rect(0, 0, w, 45, "F");
      doc.setFillColor(196, 18, 48);
      doc.rect(0, 45, w, 2, "F");

      doc.setTextColor(255, 255, 255);
      doc.setFontSize(18);
      doc.text("DMCA Takedown Notice", 20, 25);
      doc.setFontSize(8);
      doc.setTextColor(212, 168, 67);
      doc.text("Generated by ClaimMyFace.com", 20, 35);

      // Body
      doc.setTextColor(30, 30, 40);
      doc.setFontSize(10);
      const lines = doc.splitTextToSize(notice, w - 40);
      let y = 58;
      const pageH = doc.internal.pageSize.getHeight();
      for (const line of lines) {
        if (y > pageH - 20) {
          doc.addPage();
          y = 20;
        }
        doc.text(line, 20, y);
        y += 5;
      }

      doc.save("DMCA-Notice.pdf");
      toast({ title: "PDF downloaded" });
    } catch (err: any) {
      toast({ title: "PDF failed", description: err.message, variant: "destructive" });
    }
  }, [notice, toast]);

  if (loading) {
    return (
      <DashboardLayout>
        <div className="flex items-center justify-center py-20">
          <Loader2 className="w-6 h-6 animate-spin text-primary" />
        </div>
      </DashboardLayout>
    );
  }

  return (
    <DashboardLayout>
      <div className="max-w-3xl mx-auto space-y-8">
        <div className="flex items-center gap-3">
          <FileText className="w-8 h-8 text-destructive" />
          <h1 className="font-display text-3xl font-bold">DMCA Generator</h1>
        </div>

        {/* Form */}
        <Card className="glass-card border-border/30">
          <CardContent className="p-6 space-y-5">
            <h2 className="font-display text-lg font-semibold">Generate a DMCA Takedown Notice</h2>

            <div className="grid gap-4 sm:grid-cols-2">
              <div className="space-y-2">
                <Label>Your Legal Name *</Label>
                <Input value={form.legal_name} onChange={(e) => setForm((f) => ({ ...f, legal_name: e.target.value }))} />
              </div>
              <div className="space-y-2">
                <Label>Your Contact Email *</Label>
                <Input value={form.email} onChange={(e) => setForm((f) => ({ ...f, email: e.target.value }))} />
              </div>
              <div className="space-y-2">
                <Label>Platform *</Label>
                <Select value={form.platform} onValueChange={(v) => setForm((f) => ({ ...f, platform: v }))}>
                  <SelectTrigger><SelectValue placeholder="Select platform" /></SelectTrigger>
                  <SelectContent>
                    {PLATFORMS.map((p) => <SelectItem key={p} value={p}>{p}</SelectItem>)}
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-2">
                <Label>URL of Infringing Content *</Label>
                <Input
                  placeholder="https://..."
                  value={form.infringing_url}
                  onChange={(e) => setForm((f) => ({ ...f, infringing_url: e.target.value }))}
                />
              </div>
              <div className="space-y-2 sm:col-span-2">
                <Label>Description of Your Original Work *</Label>
                <Textarea
                  placeholder="Describe the copyrighted work being infringed (your likeness, voice, performance, etc.)..."
                  value={form.description}
                  onChange={(e) => setForm((f) => ({ ...f, description: e.target.value }))}
                  rows={4}
                />
              </div>
            </div>

            <Button onClick={generateNotice} disabled={generating} className="font-display bg-destructive hover:bg-destructive/90">
              {generating ? <Loader2 className="w-4 h-4 animate-spin mr-2" /> : <FileText className="w-4 h-4 mr-2" />}
              Generate DMCA Notice
            </Button>
          </CardContent>
        </Card>

        {/* Generated Notice */}
        {notice && (
          <Card className="glass-card border-border/30">
            <CardContent className="p-6 space-y-4">
              <h2 className="font-display text-lg font-semibold">Your DMCA Notice</h2>
              <div className="bg-card/60 border border-border/40 rounded-lg p-4 max-h-[500px] overflow-y-auto">
                <pre className="text-sm whitespace-pre-wrap font-sans text-foreground leading-relaxed">{notice}</pre>
              </div>
              <div className="flex flex-wrap gap-3">
                <Button onClick={copyToClipboard} variant="secondary" className="font-display">
                  <Copy className="w-4 h-4 mr-2" /> Copy to Clipboard
                </Button>
                <Button onClick={downloadPDF} className="font-display">
                  <Download className="w-4 h-4 mr-2" /> Download as PDF
                </Button>
              </div>
            </CardContent>
          </Card>
        )}
      </div>
    </DashboardLayout>
  );
};

export default DmcaGeneratorPage;
