
-- 1. Make headshots bucket private
UPDATE storage.buckets SET public = false WHERE id = 'headshots';

-- Existing owner INSERT/UPDATE/DELETE/SELECT policies on storage.objects remain.
-- (A "Owners can list own headshots" SELECT policy already scopes to the owning folder.)

-- 2. Retire previous legal docs and insert new versions
UPDATE public.legal_documents SET is_active = false
  WHERE document_type IN ('terms', 'likeness_rights') AND is_active = true;

INSERT INTO public.legal_documents (document_type, title, version, is_active, content) VALUES
('terms', 'Terms of Service', 2, true,
'ClaimMyFace is an identity monitoring and registration service provided by Roberts Entertainment / PerformersappAI. By creating an account and using this platform you agree to the following terms.

1. ELIGIBILITY & OWNERSHIP. You confirm that you are the rightful owner of the identity, likeness, name, and voice you register, and that you have the legal right to upload any photo, audio, or other material you submit.

2. PHOTO UPLOAD LICENSE. By uploading a headshot or other photograph, you grant ClaimMyFace a worldwide, non-exclusive, revocable license to store, hash, transmit, and submit that image to third-party reverse image search and identity monitoring services solely for the purpose of detecting unauthorized use of your likeness on your behalf. We do not sell or license your photos to advertisers or AI training providers.

3. NO BIOMETRIC PROCESSING. ClaimMyFace does not perform facial recognition, does not generate biometric identifiers from your photos, and does not store biometric templates. Photos are used only for visual similarity matching and human review.

4. DMCA / TAKEDOWN & UNAUTHORIZED UPLOADS. If you upload an image, audio file, or other content that you do not own or do not have permission to use, you are solely responsible for any resulting claims. If you believe content on ClaimMyFace infringes your rights, send a takedown request to dmca@claimmyface.com including (a) a description of the work, (b) the location on ClaimMyFace, (c) your contact information, and (d) a good-faith statement of ownership. We will review and act on valid requests promptly.

5. NOT LEGAL ADVICE. ClaimMyFace is not a law firm. Scan results, reports, certificates, and generated notices are informational only and do not constitute legal advice or legal evidence without independent verification.

6. ACCEPTABLE USE. You are responsible for how you use any reports, notices, or certificates generated by the platform. ClaimMyFace may suspend or remove accounts that upload false, misleading, unauthorized, or abusive material, including identities you do not own.

7. DATA DELETION. You may request deletion of your account and uploaded material at any time from Settings or by contacting support@claimmyface.com.'),

('likeness_rights', 'Likeness Rights Agreement', 2, true,
'By registering your headshot, voice sample, and identifying information with ClaimMyFace, you confirm that you are the sole legal owner of the identity being registered and that you have the right to authorize its use as described below.

1. PURPOSE. ClaimMyFace stores and processes your uploaded photos and voice samples solely to monitor for unauthorized public use of your likeness across the open web and supported platforms.

2. NO FACIAL RECOGNITION OR BIOMETRIC PROFILING. ClaimMyFace does not perform facial recognition and does not create or store biometric identifiers. Photos are used for visual similarity matching only.

3. NO SALE OR THIRD-PARTY SHARING. ClaimMyFace will never sell, license, or share your uploaded photos, voice samples, or contact information with advertisers, data brokers, or AI training providers.

4. UPLOAD RESPONSIBILITY. You warrant that every image and recording you upload is one you own or have explicit permission to use. You are solely responsible for unauthorized uploads. Takedown requests may be sent to dmca@claimmyface.com.

5. REVOCATION & DELETION. You may revoke this agreement and request deletion of your uploaded material at any time from Settings.');
